<?php

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
	include('credentials.inc.php');
	global $credential;

	if (!isset($_POST['credential'])) {
		http_response_code(401);
		echo '401 unauthorized';
		return;
	}

	if ($_POST['credential'] != $credential) {
		http_response_code(403);
		echo '403 Not allowed';
		return;
	}


	header('Content-Type: application/json');
	header('Access-Control-Allow-Origin: *');


	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'https://www.transilien.com/api/stopareas');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

	curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

	$headers = array();
	$headers[] = 'Connection: keep-alive';
	$headers[] = 'Pragma: no-cache';
	$headers[] = 'Cache-Control: no-cache';
	$headers[] = 'Upgrade-Insecure-Requests: 1';
	$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36';
	$headers[] = 'Accept: image/avif,image/webp,image/apng,image/*,*/*;q=0.8';
	$headers[] = 'Sec-Fetch-Site: same-origin';
	$headers[] = 'Sec-Fetch-Mode: no-cors';
	$headers[] = 'Sec-Fetch-User: ?1';
	$headers[] = 'Sec-Fetch-Dest: image';
	$headers[] = 'Accept-Language: fr';
	$headers[] = 'Cookie: TRIPRD1TRIABIP11=triabip11tri; TRIPRD1WAS=triabip11esi; TRI_city=LIL_PRD1; has_js=1; _ga=GA1.2.394215572.1599122941; _gid=GA1.2.215561751.1599122941; _JSESSIONID=4FBF56D6F32B4DD2A481148268CB6E51; TRIPRD1CMSD8=triyzep61tricms; OptanonAlertBoxClosed=2020-09-03T09:22:03.980Z; OptanonConsent=isIABGlobal=false&datestamp=Thu+Sep+03+2020+12%3A16%3A19+GMT%2B0200+(%E4%B8%AD%E6%AC%A7%E5%A4%8F%E4%BB%A4%E6%97%B6%E9%97%B4)&version=5.10.0&landingPath=NotLandingPage&groups=1%3A1%2C2%3A1%2C3%3A1&hosts=&consentId=32b6cabf-c7ac-4369-a677-5d07bc01913d&interactionCount=1&AwaitingReconsent=false&geolocation=%3B';
	$headers[] = 'Referer: ';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);

	echo $result;
}
